layout_spectrum: 1
color:
  saturation: 0.2120018
  lightness: 0.302817
  brandStrength: 0.7683688
  brandColors:
    - '#FCFCFC'
    - '#191816'
    - '#615C56'
    - '#B3B3AB'
    - '#8E8A81'
  rhythmicContrast: 0.3194417
typography_spectrum: 0.5247046
name: Sarah Carter Creative
